language: node_js
node_js:
  - 12
branches:
  only:
  - master
before_script:
- npm install -g @ionic/cli
script:
- npm install
- ionic build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
