language: node_js
node_js:
- '11.0'
branches:
  only:
  - master
before_script:
- npm install -g ionic
script:
- npm install
- ionic build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "XBKHj6BYpFpM2p8BCXvhQt1bTlMoZGx4e0uHc0VoqNbrl9POq43WJMPMqF5Y0AL+PA4slRaNnSrpEOAt0TqDn2wwVHsevHdGJiskTy7BE+cXiK7iVsau6yQNtVffe5/xBvUVEUPN3HQpe1nLaNDYg8VnB3dx3yjQmgK5v+zMsZxw6r3eo3iJPAvrQRI6CDByd+LRVx+CMx6VQ0Slgk4XT0Tub3Nl4IfMODOj0V6Y9VZp50BayAqFMaERqSdxT5wriL73ymSK8Co5AjU3zB+mOTkl8MQ3xTXutXU6ohPZynX8+I0OG5GeR1ikRdmFP3T1OM3HrEGAX4D9NIax7i2VDQfrtv/i5d0IvK1cF+T/7Uvk60k9GjnRzWywiZOJgCUwYkcvTPgHBAevo3iEz0kYg8gKo1dkSYa99qkpJXERcxDhFJayZhXTNccs7xxaeG5zz5hXUK1rJyRWS2wUYZN5U8cUn88lA8JlVlEvxH2lmoW/J0p0wgxx8EUF0Cn3AEFTVhF8cyp5Qwv5RozUGGNEyed7DbPhYnwyPAnoz0TJ2Yq2lv1c8CcxOoEzWjrGhvrC0Mn18/SiYM4wDt0nTLMHPCRSaL21E5hNa/bfkKt7tsbIl+2pCDTAzuhYYR6hm6t2Tp6SZWOn9fEcwEFheTXhckvtqV3mynsfcpvx5brsT78="